<?php

namespace Database\Factories;

use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class ProductFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Product::class;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'name' => $this->faker->randomElement([
                    "Aba",
                    "Abho",
                    "Abaya",
                    "Academic costume",
                    "Achkan",
                    "Afghan",
                    "A line skirt",
                    "Alice band",
                    "Angarakha",
                    "Alice band",
                    "Aloha shirt",
                    "Apple hats",
                    "Apron",
                    "Apron dress",
                    "Advancing colours",
                    "American style",
                    "Angel Flight suit",
                    "Angel sleeved blouse",
                    "Antebellum waist",
                    "Ankle length Pants",
                    "Anklet",
                    "Anorak",
                    "Apache Tie",
                    "Armlet",
                    "Armband",
                    "Ascot",
                    "Babushka",
                    "Baby Bonnet",
                    "Baby bunting",
                    "Baby doll dress",
                    "Babykini",
                    "Baggy pants",
                    "Ball Gown",
                    "Balmacaan",
                    "Bandana",
                    "Bandeau",
                    "Bandeau top",
                    "Ballet skirt/ Ballerina skirt",
                    "Barfly apparel",
                    "Barn jacket",
                    "Basque waistline",
                    "Barrow coat",
                    "Bathing cap",
                    "Bathing suit",
                    "Bathrobe",
                    "Beach Pajamas",
                    "Bed Jacket",
                    "Bell bottom pants",
                    "Bell Boy Jacket",
                    "Belt",
                    "Bermuda Shorts",
                    "Bertha collar",
                    "Bias Slip",
                    "Bias skirt",
                    "Bike Tards",
                    "Bikini",
                    "Bishop sleeve",
                    "Bisht",
                    "Blazer (sports jacket)",
                    "Bloomers",
                    "Blouse",
                    "Blouson",
                    "Bodycon dress",
                    "Bohemian style / Boho chic",
                    "Bolero Jacket",
                    "Bomber jacket",
                    "Bondage pants",
                    "Bootcut",
                    "Boots",
                    "Bow blouses",
                    "Bow Tie",
                    "Boxers",
                    "Boyfriend cut",
                    "Boyfriend jeans",
                    "Boyshorts",
                    "Bow tie",
                    "Bra/ Brassiere",
                    "Bra & KnickerSet",
                    "Bralette",
                    "Briefs",
                    "Brothel creeper shoes",
                    "Brush train",
                    "Burkha",
                    "Burnoose",
                    "Bushirt sleeve",
                    "Bush Jacket",
                    "Business suit",
                    "Bustier",
                    "Bustle",
                    "Button down shirt",
                    "Bicycle clothing",
                    "Brunswick",
                    "Camisole / Camisole tops",
                    "Cap",
                    "Cape",
                    "Capelet sleeve",
                    "Capelet train",
                    "Capri Pants",
                    "Cardigan",
                    "Cargos",
                    "Car coat",
                    "Carpenter style",
                    "Car wash skirt",
                    "Catsuit",
                    "Cathedral train",
                    "Chemise",
                    "Chesterfield coat",
                    "Circle skirt",
                    "Cloche",
                    "Cloak",
                    "Cocktail dress",
                    "Coif",
                    "Compression tights",
                    "Co-ordinates",
                    "Cossack",
                    "Corset",
                    "Court train",
                    "Cover-up",
                    "Covert coat",
                    "Cowl Neck style",
                    "Cravat",
                    "Crew neck",
                    "Cropped jacket",
                    "Crop top",
                    "Cufflinks",
                    "Culottes",
                    "Cummerbund",
                    "Debutante dress",
                    "Dickey",
                    "Dinner Jacket",
                    "Divided skirt",
                    "Djelleba",
                    "Dolman sleeve",
                    "Double breasted style jacket",
                    "Doublet",
                    "Drape front",
                    "Dress",
                    "Dressing Gown",
                    "Dress Shirt",
                    "Drindle skirt",
                    "Drainpipe pant",
                    "Dropped Waist / Low Waist style ",
                    "Drop shoulder sleeved bodice",
                    "Duffel Coat",
                    "Duster coat",
                    "Dupatta ( Odhani / Chunri)",
                    "Dungarees",
                    "Eastern pants",
                    "Eisenhower Jacket",
                    "Elephantine pants",
                    "Empire waistband/ empire line style",
                    "Envelope waist style",
                    "Epaulet",
                    "Epaulet shirt",
                    "Eton Jacket",
                    "Fanny wrap",
                    "Fingerless gloves",
                    "Fishtail Train",
                    "Fit and Flare skirt",
                    "Fit & Flare clothing",
                    "Flannel shirt",
                    "Fleece",
                    "Foot socks / Footsies/ Footies",
                    "French pantyhose",
                    "Full Slips:",
                    "Fur coat",
                    "Gaiter",
                    "Gallous",
                    "Gaghra",
                    "Garcon look",
                    "Garter Belts",
                    "Wedding Garter",
                    "Gartini",
                    "Gaucho pants",
                    "Gibson sleeve",
                    "Girdle",
                    "Gloves",
                    "Gore (Gusset)",
                    "Gored skirt",
                    "Granny Dress",
                    "Grunge",
                    "G string",
                    "Half slip",
                    "Handkerchief skirt",
                    "Harem pants",
                    "Halterneck",
                    "Hat",
                    "Hawaiian shirt",
                    "Head dress",
                    "Henley shirt",
                    "Hijab",
                    "High waist",
                    "Hip hugger",
                    "Hip rider skirt",
                    "Hipster",
                    "Hippie style",
                    "Hobble skirt",
                    "Hollywood Waistband",
                    "Hoop skirt",
                    "Hoody",
                    "Hosiery",
                    "House coat",
                    "Hug me tight",
                    "Infinity scarf",
                    "Jacket",
                    "Jardigan",
                    "Jeans",
                    "Jeggings",
                    "Jester blouse",
                    "Jilbab",
                    "Jogging Suit",
                    "Jodhpurs",
                    "Jorts",
                    "Jumper",
                    "Khimar",
                    "Kick pleated skirts",
                    "Kimono",
                    "Kimono Jacket",
                    "Kaftan (Caftan)",
                    "Kaffiyeh",
                    "Kilt",
                    "Kipper tie",
                    "Knickers",
                    "Knee Grazer",
                    "Knee high socks",
                    "Knickers",
                    "Kurta",
                    "Leggings (tights)",
                    "Leg warmer",
                    "Lehanga ( Ghagra)",
                    "Lederhosen",
                    "Leotard",
                    "Lingerie",
                    "Long Johns",
                    "Lounge wear",
                    "Lounge pants",
                    "Low waist",
                    "Lycee",
                    "Macintosh",
                    "Marine look",
                    "Mailot",
                    "Mandals",
                    "Mantle",
                    "Maternity wear",
                    "Maxi",
                    "Meggings",
                    "Men Mermaid style",
                    "Merry widow",
                    "Midi Skirt",
                    "Middy blouse",
                    "Military Belt",
                    "Mitt",
                    "Mittens",
                    "Negligee",
                    "Nightgown",
                    "Nightwear",
                    "Niqab",
                    "Obi / Obi belt",
                    "Off-The-Shoulder Neckline style",
                    "Oilskin clothing",
                    "Overalls",
                    "Overskirt",
                    "Padded Bra",
                    "Pajama pants",
                    "Palazzo pants",
                    "Panel skirt",
                    "Pannier",
                    "Pant liner",
                    "Panti liner",
                    "Panty",
                    "Pantyhose",
                    "Parkha",
                    "Pashmina",
                    "Peacoat",
                    "Peasant Top",
                    "Pedal pushers",
                    "Peek-a-boo style",
                    "Pegged skirt",
                    "Peignoir",
                    "Pelisse",
                    "Pencil skirt",
                    "Peplum",
                    "Petticoat",
                    "Pheran",
                    "Photo tshirts ",
                    "Pinafore",
                    "Play suit",
                    "Plunge",
                    "Plus size ( Queen Size)",
                    "Poet sleeve",
                    "Polo Shirt",
                    "Poncho",
                    "Ponte",
                    "Princess Line",
                    "Psychedelic",
                    "Puckered bodice",
                    "Pull on clothes",
                    "Pullover",
                    "Punk Pants",
                    "Push up Bras",
                    "Pyjamas",
                    "Qipao",
                    "Racer Back",
                    "Raccoon coat",
                    "Rain Coat",
                    "Raglan",
                    "Rebozo",
                    "Reefer",
                    "Reversible",
                    "Riding habit",
                    "Robe",
                    "Romper",
                    "Ruana",
                    "Running shorts",
                    "Sack dress",
                    "Sacque",
                    "Safari shirt",
                    "Safari suit",
                    "Sari",
                    "Sark",
                    "Sailor pants",
                    "Sailor suit",
                    "Sarong",
                    "Sash",
                    "Seamless panties",
                    "Separates",
                    "Scarf",
                    "Scooter",
                    "Shape wear ( Waist nipper)",
                    "Shawl",
                    "Sharrara",
                    "Sheath",
                    "Shellsuit",
                    "Shervani",
                    "Shift Dress",
                    "Shinos",
                    "Shirt",
                    "Shorts",
                    "Shrug",
                    "Singlet",
                    "Slip",
                    "Ski Pants",
                    "Skimmer pants",
                    "Skirt",
                    "Skirtini",
                    "Sheath dress",
                    "Shift dress",
                    "Shirred waist",
                    "Shirtwaist dress",
                    "Short shorts / hot pants",
                    "Skort",
                    "Slip dress",
                    "Smoking jacket",
                    "Socks",
                    "Spants",
                    "Spencer",
                    "Split skirt",
                    "Stadium coat",
                    "Stockings",
                    "Stole",
                    "Stirrup pants",
                    "Strapless Bodice",
                    "Straight pants",
                    "Straight skirt",
                    "Stretch slip",
                    "Suit",
                    "Summer Cardigan",
                    "Surplice",
                    "Surplice",
                    "Suspenders",
                    "Swacket",
                    "Sweater",
                    "Sweatshirt",
                    "Sweats",
                    "Sweep train",
                    "Swimming Costume",
                    "Swimming Shorts",
                    "Swimming Trunks",
                    "Tap pants",
                    "T-Shirt",
                    "Tailcoat male",
                    "Tagiyah",
                    "Tankini",
                    "Tank top",
                    "Tent/ Trapese/ Swing dress",
                    "Thong",
                    "Thobe / Thawb (Dishdasha / Kandora)",
                    "Thigh high stockings",
                    "Thermal shirts",
                    "Tie",
                    "Tiered skirt",
                    "Tights",
                    "Top",
                    "Toreador pants",
                    "Tracksuit",
                    "Trainers",
                    "Treggings",
                    "Trench Coat",
                    "Trousers",
                    "Trumpet skirt",
                    "Trousseau",
                    "Tubular Scarf (Circular scarf /snood)",
                    "Tucked in blouse",
                    "Tulip hemmed skirt",
                    "Tummy shaper",
                    "Tunic",
                    "Turban",
                    "Turtleneck",
                    "Tuxedo Jacket ",
                    "Tuxedo",
                    "Twin set",
                    "Ulster",
                    "Underwear",
                    "Uniform",
                    "Union suit",
                    "Unitard",
                    "Veil",
                    "Waistcoat",
                    "Watteau",
                    "Windsor Tie",
                    "Wrap around skirt",
                    "Whorts",
                    "Wind Pants",
                    "Wrap coat",
                    "Wylie coat",
                    "Yoga Pants",
                    "Zip"
                ]
        ),
            'price' => $this->faker->randomFloat(2,1,100),
        ];
    }
}
